If there is a problem with selecting kernel of ipynb in vscode, try reinstalling some vscode extensions: Python, Pylance, Jupyter. Please follow this [post](https://github.com/microsoft/vscode-jupyter/issues/10043#issuecomment-1429290022)

In [1]:
import collections
import os

import numpy as np
import pandas as pd
from sklearn.utils.class_weight import compute_class_weight

In [2]:
INPUT_PATH = '/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split{}'
N_SPLITS = 3

In [3]:
cnt_dict = {}
list_of_categories = None

for split_id in range(N_SPLITS):
  SPLIT_PATH = INPUT_PATH.format(split_id)
  cnt_dict[split_id] = {}
  for subset_id in ['train', 'val', 'test']:
    cnt_dict[split_id][subset_id] = {}
    SUBSET_PATH = os.path.join(SPLIT_PATH, subset_id)
    print(SUBSET_PATH)
    categories = os.listdir(SUBSET_PATH)
    categories.sort()
    if list_of_categories is None:
      list_of_categories = categories.copy()
    print(categories)
    for category in categories:
      CATEGORY_PATH = os.path.join(SUBSET_PATH, category)
      cur_filenames = os.listdir(CATEGORY_PATH)
      cnt_dict[split_id][subset_id][category] = len(cur_filenames)
      print(f'Split {split_id}, subset {subset_id}, class {category}, #samples {len(cur_filenames)}')

/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split0/train
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 0, subset train, class endocapillary_hypercellularity, #samples 103
Split 0, subset train, class exudative_glomerulus, #samples 25
Split 0, subset train, class fibrinoid_necrosis_glomerulus, #samples 76
Split 0, subset train, class fibrocellular_crescent, #samples 106
Split 0, subset train, class fibrous_crescent, #samples 34
Split 0, subset train, class glomerul_lipoprotein_thrombus, #samples 19
Split 0, subset train, class glomerular_adhesion, #samples 157
Split 0, subset train, class glomerular_basement_membrane_duplication_splitting, #samples 14
Split 0, subset train, class glomerular_basement_membrane_thickening, #samples 79
Split 0, subset train, class glomerular_collapse, #samples 229
Split 0, subset train, class glomerular_congestion, #samples 70
Split 0, subset train, class glomerular_foam_cell, #samples 46
Split 0, subset train, class glomerular_hyaline_pseudothrombus, #samples 28
Split 0, subset train, class glomerular_hyalinosis, #samples 114
Split 0, subset train, class glomerular_obsolesce, #samples 14
Split 0, subset train, class glomerular_segmental_sclerosis, #samples 229
Split 0, subset train, class glomerular_thrombus, #samples 97
Split 0, subset train, class glomerulomegaly, #samples 52
Split 0, subset train, class glomerulonephritis_hyaline_thrombus, #samples 35
Split 0, subset train, class glomerulus_endotheliosis, #samples 28
Split 0, subset train, class hyalin_drop_diabetic_glomerulus, #samples 8
Split 0, subset train, class immature_glomerulus, #samples 120
Split 0, subset train, class ischemic_glomerular_collapse, #samples 49
Split 0, subset train, class karyorrhexis_glomerulonephritis, #samples 17
Split 0, subset train, class membranous_nephropathy_holes, #samples 20
Split 0, subset train, class membranous_nephropathy_spikes, #samples 49
Split 0, subset train, class mesangial_hypercellularity, #samples 180
Split 0, subset train, class mesangial_matrix_expansion, #samples 332
Split 0, subset train, class mesangiolysis, #samples 76
Split 0, subset train, class nodular_sclerosis_glomerulus, #samples 97
Split 0, subset train, class parietal_cell_glomerulus, #samples 60
Split 0, subset train, class periglomerular_fibrosis, #samples 46

Split 0, subset train, class podocyte, #samples 19
Split 0, subset train, class podocyte_hyperplasia, #samples 73
Split 0, subset train, class podocyte_hypertrophy, #samples 48
Split 0, subset train, class podocyte_reabsorption_droplet, #samples 7
Split 0, subset train, class pseudocrescent, #samples 25
Split 0, subset train, class solidified_glomerular_sclerosis_global, #samples 73
Split 0, subset train, class spikes_glomerular_amyoidosis, #samples 14
Split 0, subset train, class visceral_epithelial_cell, #samples 61
Split 0, subset train, class visceral_epithelial_cell_capping, #samples 8
Split 0, subset train, class wire_loop_glomerulus, #samples 32
/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split0/val
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 0, subset val, class endocapillary_hypercellularity, #samples 34
Split 0, subset val, class exudative_glomerulus, #samples 8
Split 0, subset val, class fibrinoid_necrosis_glomerulus, #samples 25
Split 0, subset val, class fibrocellular_crescent, #samples 35
Split 0, subset val, class fibrous_crescent, #samples 12
Split 0, subset val, class glomerul_lipoprotein_thrombus, #samples 6
Split 0, subset val, class glomerular_adhesion, #samples 52
Split 0, subset val, class glomerular_basement_membrane_duplication_splitting, #samples 4
Split 0, subset val, class glomerular_basement_membrane_thickening, #samples 27
Split 0, subset val, class glomerular_collapse, #samples 76
Split 0, subset val, class glomerular_congestion, #samples 23
Split 0, subset val, class glomerular_foam_cell, #samples 16
Split 0, subset val, class glomerular_hyaline_pseudothrombus, #samples 10
Split 0, subset val, class glomerular_hyalinosis, #samples 38
Split 0, subset val, class glomerular_obsolesce, #samples 4
Split 0, subset val, class glomerular_segmental_sclerosis, #samples 77
Split 0, subset val, class glomerular_thrombus, #samples 32
Split 0, subset val, class glomerulomegaly, #samples 17
Split 0, subset val, class glomerulonephritis_hyaline_thrombus, #samples 12
Split 0, subset val, class glomerulus_endotheliosis, #samples 10
Split 0, subset val, class hyalin_drop_diabetic_glomerulus, #samples 2
Split 0, subset val, class immature_glomerulus, #samples 40
Split 0, subset val, class ischemic_glomerular_collapse, #samples 17
Split 0, subset val, class karyorrhexis_glomerulonephritis, #samples 5
Split 0, subset val, class membranous_nephropathy_holes, #samples 6
Split 0, subset val, class membranous_nephropathy_spikes, #samples 17
Split 0, subset val, class mesangial_hypercellularity, #samples 60
Split 0, subset val, class mesangial_matrix_expansion, #samples 111
Split 0, subset val, class mesangiolysis, #samples 25
Split 0, subset val, class nodular_sclerosis_glomerulus, #samples 32
Split 0, subset val, class parietal_cell_glomerulus, #samples 20
Split 0, subset val, class periglomerular_fibrosis, #samples 16
Split 0, subset val, class podocyte, #samples 7
Split 0, subset val, class podocyte_hyperplasia, #samples 24
Split 0, subset val, class podocyte_hypertrophy, #samples 16
Split 0, subset val, class podocyte_reabsorption_droplet, #samples 2
Split 0, subset val, class pseudocrescent, #samples 9
Split 0, subset val, class solidified_glomerular_sclerosis_global, #samples 25
Split 0, subset val, class spikes_glomerular_amyoidosis, #samples 4
Split 0, subset val, class visceral_epithelial_cell, #samples 21
Split 0, subset val, class visceral_epithelial_cell_capping, #samples 2
Split 0, subset val, class wire_loop_glomerulus, #samples 11
/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split0/test
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 0, subset test, class endocapillary_hypercellularity, #samples 34
Split 0, subset test, class exudative_glomerulus, #samples 8
Split 0, subset test, class fibrinoid_necrosis_glomerulus, #samples 26
Split 0, subset test, class fibrocellular_crescent, #samples 36
Split 0, subset test, class fibrous_crescent, #samples 11
Split 0, subset test, class glomerul_lipoprotein_thrombus, #samples 6
Split 0, subset test, class glomerular_adhesion, #samples 53
Split 0, subset test, class glomerular_basement_membrane_duplication_splitting, #samples 4
Split 0, subset test, class glomerular_basement_membrane_thickening, #samples 27
Split 0, subset test, class glomerular_collapse, #samples 76
Split 0, subset test, class glomerular_congestion, #samples 23
Split 0, subset test, class glomerular_foam_cell, #samples 15
Split 0, subset test, class glomerular_hyaline_pseudothrombus, #samples 9
Split 0, subset test, class glomerular_hyalinosis, #samples 38
Split 0, subset test, class glomerular_obsolesce, #samples 5
Split 0, subset test, class glomerular_segmental_sclerosis, #samples 77
Split 0, subset test, class glomerular_thrombus, #samples 32
Split 0, subset test, class glomerulomegaly, #samples 17
Split 0, subset test, class glomerulonephritis_hyaline_thrombus, #samples 12
Split 0, subset test, class glomerulus_endotheliosis, #samples 10
Split 0, subset test, class hyalin_drop_diabetic_glomerulus, #samples 3
Split 0, subset test, class immature_glomerulus, #samples 40
Split 0, subset test, class ischemic_glomerular_collapse, #samples 16
Split 0, subset test, class karyorrhexis_glomerulonephritis, #samples 5
Split 0, subset test, class membranous_nephropathy_holes, #samples 6
Split 0, subset test, class membranous_nephropathy_spikes, #samples 16
Split 0, subset test, class mesangial_hypercellularity, #samples 60
Split 0, subset test, class mesangial_matrix_expansion, #samples 111
Split 0, subset test, class mesangiolysis, #samples 26
Split 0, subset test, class nodular_sclerosis_glomerulus, #samples 33
Split 0, subset test, class parietal_cell_glomerulus, #samples 20
Split 0, subset test, class periglomerular_fibrosis, #samples 15
Split 0, subset test, class podocyte, #samples 6
Split 0, subset test, class podocyte_hyperplasia, #samples 25
Split 0, subset test, class podocyte_hypertrophy, #samples 16
Split 0, subset test, class podocyte_reabsorption_droplet, #samples 2
Split 0, subset test, class pseudocrescent, #samples 8
Split 0, subset test, class solidified_glomerular_sclerosis_global, #samples 24
Split 0, subset test, class spikes_glomerular_amyoidosis, #samples 5
Split 0, subset test, class visceral_epithelial_cell, #samples 20
Split 0, subset test, class visceral_epithelial_cell_capping, #samples 3
Split 0, subset test, class wire_loop_glomerulus, #samples 11
/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split1/train
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 1, subset train, class endocapillary_hypercellularity, #samples 103
Split 1, subset train, class exudative_glomerulus, #samples 25
Split 1, subset train, class fibrinoid_necrosis_glomerulus, #samples 76
Split 1, subset train, class fibrocellular_crescent, #samples 106
Split 1, subset train, class fibrous_crescent, #samples 34
Split 1, subset train, class glomerul_lipoprotein_thrombus, #samples 19
Split 1, subset train, class glomerular_adhesion, #samples 157
Split 1, subset train, class glomerular_basement_membrane_duplication_splitting, #samples 14
Split 1, subset train, class glomerular_basement_membrane_thickening, #samples 79
Split 1, subset train, class glomerular_collapse, #samples 229
Split 1, subset train, class glomerular_congestion, #samples 70
Split 1, subset train, class glomerular_foam_cell, #samples 46
Split 1, subset train, class glomerular_hyaline_pseudothrombus, #samples 28
Split 1, subset train, class glomerular_hyalinosis, #samples 114
Split 1, subset train, class glomerular_obsolesce, #samples 14
Split 1, subset train, class glomerular_segmental_sclerosis, #samples 229
Split 1, subset train, class glomerular_thrombus, #samples 97
Split 1, subset train, class glomerulomegaly, #samples 52
Split 1, subset train, class glomerulonephritis_hyaline_thrombus, #samples 35
Split 1, subset train, class glomerulus_endotheliosis, #samples 28
Split 1, subset train, class hyalin_drop_diabetic_glomerulus, #samples 8
Split 1, subset train, class immature_glomerulus, #samples 120
Split 1, subset train, class ischemic_glomerular_collapse, #samples 49
Split 1, subset train, class karyorrhexis_glomerulonephritis, #samples 17
Split 1, subset train, class membranous_nephropathy_holes, #samples 20
Split 1, subset train, class membranous_nephropathy_spikes, #samples 49
Split 1, subset train, class mesangial_hypercellularity, #samples 180
Split 1, subset train, class mesangial_matrix_expansion, #samples 332
Split 1, subset train, class mesangiolysis, #samples 76
Split 1, subset train, class nodular_sclerosis_glomerulus, #samples 97
Split 1, subset train, class parietal_cell_glomerulus, #samples 60
Split 1, subset train, class periglomerular_fibrosis, #samples 46
Split 1, subset train, class podocyte, #samples 19
Split 1, subset train, class podocyte_hyperplasia, #samples 73
Split 1, subset train, class podocyte_hypertrophy, #samples 48
Split 1, subset train, class podocyte_reabsorption_droplet, #samples 7
Split 1, subset train, class pseudocrescent, #samples 25
Split 1, subset train, class solidified_glomerular_sclerosis_global, #samples 73
Split 1, subset train, class spikes_glomerular_amyoidosis, #samples 14
Split 1, subset train, class visceral_epithelial_cell, #samples 61
Split 1, subset train, class visceral_epithelial_cell_capping, #samples 8
Split 1, subset train, class wire_loop_glomerulus, #samples 32
/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split1/val
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 1, subset val, class endocapillary_hypercellularity, #samples 34
Split 1, subset val, class exudative_glomerulus, #samples 8
Split 1, subset val, class fibrinoid_necrosis_glomerulus, #samples 25
Split 1, subset val, class fibrocellular_crescent, #samples 35
Split 1, subset val, class fibrous_crescent, #samples 12
Split 1, subset val, class glomerul_lipoprotein_thrombus, #samples 6
Split 1, subset val, class glomerular_adhesion, #samples 52
Split 1, subset val, class glomerular_basement_membrane_duplication_splitting, #samples 4
Split 1, subset val, class glomerular_basement_membrane_thickening, #samples 27
Split 1, subset val, class glomerular_collapse, #samples 76
Split 1, subset val, class glomerular_congestion, #samples 23
Split 1, subset val, class glomerular_foam_cell, #samples 16
Split 1, subset val, class glomerular_hyaline_pseudothrombus, #samples 10
Split 1, subset val, class glomerular_hyalinosis, #samples 38
Split 1, subset val, class glomerular_obsolesce, #samples 4
Split 1, subset val, class glomerular_segmental_sclerosis, #samples 77
Split 1, subset val, class glomerular_thrombus, #samples 32
Split 1, subset val, class glomerulomegaly, #samples 17
Split 1, subset val, class glomerulonephritis_hyaline_thrombus, #samples 12
Split 1, subset val, class glomerulus_endotheliosis, #samples 10
Split 1, subset val, class hyalin_drop_diabetic_glomerulus, #samples 2
Split 1, subset val, class immature_glomerulus, #samples 40
Split 1, subset val, class ischemic_glomerular_collapse, #samples 17
Split 1, subset val, class karyorrhexis_glomerulonephritis, #samples 5
Split 1, subset val, class membranous_nephropathy_holes, #samples 6
Split 1, subset val, class membranous_nephropathy_spikes, #samples 17
Split 1, subset val, class mesangial_hypercellularity, #samples 60
Split 1, subset val, class mesangial_matrix_expansion, #samples 111
Split 1, subset val, class mesangiolysis, #samples 25
Split 1, subset val, class nodular_sclerosis_glomerulus, #samples 32
Split 1, subset val, class parietal_cell_glomerulus, #samples 20
Split 1, subset val, class periglomerular_fibrosis, #samples 16
Split 1, subset val, class podocyte, #samples 7
Split 1, subset val, class podocyte_hyperplasia, #samples 25
Split 1, subset val, class podocyte_hypertrophy, #samples 16
Split 1, subset val, class podocyte_reabsorption_droplet, #samples 2
Split 1, subset val, class pseudocrescent, #samples 9
Split 1, subset val, class solidified_glomerular_sclerosis_global, #samples 24
Split 1, subset val, class spikes_glomerular_amyoidosis, #samples 4
Split 1, subset val, class visceral_epithelial_cell, #samples 21
Split 1, subset val, class visceral_epithelial_cell_capping, #samples 2
Split 1, subset val, class wire_loop_glomerulus, #samples 11
/data/hqvo3/Datasets/vlm/ml-scripts/datasets/glom_refine_splits/split1/test
['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus']
Split 1, subset test, class endocapillary_hypercellularity, #samples 34
Split 1, subset test, class exudative_glomerulus, #samples 8
Split 1, subset test, class fibrinoid_necrosis_glomerulus, #samples 26
Split 1, subset test, class fibrocellular_crescent, #samples 36
Split 1, subset test, class fibrous_crescent, #samples 11
Split 1, subset test, class glomerul_lipoprotein_thrombus, #samples 6
Split 1, subset test, class glomerular_adhesion, #samples 53
Split 1, subset test, class glomerular_basement_membrane_duplication_splitting, #samples 4
Split 1, subset test, class glomerular_basement_membrane_thickening, #samples 27
Split 1, subset test, class glomerular_collapse, #samples 76
Split 1, subset test, class glomerular_congestion, #samples 23
Split 1, subset test, class glomerular_foam_cell, #samples 15
Split 1, subset test, class glomerular_hyaline_pseudothrombus, #samples 9
Split 1, subset test, class glomerular_hyalinosis, #samples 38
Split 1, subset test, class glomerular_obsolesce, #samples 5
Split 1, subset test, class glomerular_segmental_sclerosis, #samples 77
Split 1, subset test, class glomerular_thrombus, #samples 32
Split 1, subset test, class glomerulomegaly, #samples 17
Split 1, subset test, class glomerulonephritis_hyaline_thrombus, #samples 12
Split 1, subset test, class glomerulus_endotheliosis, #samples 10
Split 1, subset test, class hyalin_drop_diabetic_glomerulus, #samples 3
Split 1, subset test, class immature_glomerulus, #samples 40
Split 1, subset test, class ischemic_glomerular_collapse, #samples 16
Split 1, subset test, class karyorrhexis_glomerulonephritis, #samples 5

In [5]:
list_of_categories

['endocapillary_hypercellularity',
 'exudative_glomerulus',
 'fibrinoid_necrosis_glomerulus',
 'fibrocellular_crescent',
 'fibrous_crescent',
 'glomerul_lipoprotein_thrombus',
 'glomerular_adhesion',
 'glomerular_basement_membrane_duplication_splitting',
 'glomerular_basement_membrane_thickening',
 'glomerular_collapse',
 'glomerular_congestion',
 'glomerular_foam_cell',
 'glomerular_hyaline_pseudothrombus',
 'glomerular_hyalinosis',
 'glomerular_obsolesce',
 'glomerular_segmental_sclerosis',
 'glomerular_thrombus',
 'glomerulomegaly',
 'glomerulonephritis_hyaline_thrombus',
 'glomerulus_endotheliosis',
 'hyalin_drop_diabetic_glomerulus',
 'immature_glomerulus',
 'ischemic_glomerular_collapse',
 'karyorrhexis_glomerulonephritis',
 'membranous_nephropathy_holes',
 'membranous_nephropathy_spikes',
 'mesangial_hypercellularity',
 'mesangial_matrix_expansion',
 'mesangiolysis',
 'nodular_sclerosis_glomerulus',
 'parietal_cell_glomerulus',
 'periglomerular_fibrosis',
 'podocyte',
 'podocyte_hyperplasia',
 'podocyte_hypertrophy',
 'podocyte_reabsorption_droplet',
 'pseudocrescent',
 'solidified_glomerular_sclerosis_global',
 'spikes_glomerular_amyoidosis',
 'visceral_epithelial_cell',
 'visceral_epithelial_cell_capping',
 'wire_loop_glomerulus']

In [6]:
# OrderedDict is dictionary with sorted keys so that when using loop to print, it will print in the sorted alphabetical order of keys
train_ordered_dict_0 = collections.OrderedDict(sorted(cnt_dict[0]['train'].items()))
val_ordered_dict_0 = collections.OrderedDict(sorted(cnt_dict[0]['val'].items()))
test_ordered_dict_0 = collections.OrderedDict(sorted(cnt_dict[0]['test'].items()))

train_ordered_dict_1 = collections.OrderedDict(sorted(cnt_dict[1]['train'].items()))
val_ordered_dict_1 = collections.OrderedDict(sorted(cnt_dict[1]['val'].items()))
test_ordered_dict_1 = collections.OrderedDict(sorted(cnt_dict[1]['test'].items()))

train_ordered_dict_2 = collections.OrderedDict(sorted(cnt_dict[2]['train'].items()))
val_ordered_dict_2 = collections.OrderedDict(sorted(cnt_dict[2]['val'].items()))
test_ordered_dict_2 = collections.OrderedDict(sorted(cnt_dict[2]['test'].items()))

In [7]:
print(test_ordered_dict_0.keys())
print(test_ordered_dict_0.items())

odict_keys(['endocapillary_hypercellularity', 'exudative_glomerulus', 'fibrinoid_necrosis_glomerulus', 'fibrocellular_crescent', 'fibrous_crescent', 'glomerul_lipoprotein_thrombus', 'glomerular_adhesion', 'glomerular_basement_membrane_duplication_splitting', 'glomerular_basement_membrane_thickening', 'glomerular_collapse', 'glomerular_congestion', 'glomerular_foam_cell', 'glomerular_hyaline_pseudothrombus', 'glomerular_hyalinosis', 'glomerular_obsolesce', 'glomerular_segmental_sclerosis', 'glomerular_thrombus', 'glomerulomegaly', 'glomerulonephritis_hyaline_thrombus', 'glomerulus_endotheliosis', 'hyalin_drop_diabetic_glomerulus', 'immature_glomerulus', 'ischemic_glomerular_collapse', 'karyorrhexis_glomerulonephritis', 'membranous_nephropathy_holes', 'membranous_nephropathy_spikes', 'mesangial_hypercellularity', 'mesangial_matrix_expansion', 'mesangiolysis', 'nodular_sclerosis_glomerulus', 'parietal_cell_glomerulus', 'periglomerular_fibrosis', 'podocyte', 'podocyte_hyperplasia', 'podocyte_hypertrophy', 'podocyte_reabsorption_droplet', 'pseudocrescent', 'solidified_glomerular_sclerosis_global', 'spikes_glomerular_amyoidosis', 'visceral_epithelial_cell', 'visceral_epithelial_cell_capping', 'wire_loop_glomerulus'])
odict_items([('endocapillary_hypercellularity', 34), ('exudative_glomerulus', 8), ('fibrinoid_necrosis_glomerulus', 26), ('fibrocellular_crescent', 36), ('fibrous_crescent', 11), ('glomerul_lipoprotein_thrombus', 6), ('glomerular_adhesion', 53), ('glomerular_basement_membrane_duplication_splitting', 4), ('glomerular_basement_membrane_thickening', 27), ('glomerular_collapse', 76), ('glomerular_congestion', 23), ('glomerular_foam_cell', 15), ('glomerular_hyaline_pseudothrombus', 9), ('glomerular_hyalinosis', 38), ('glomerular_obsolesce', 5), ('glomerular_segmental_sclerosis', 77), ('glomerular_thrombus', 32), ('glomerulomegaly', 17), ('glomerulonephritis_hyaline_thrombus', 12), ('glomerulus_endotheliosis', 10), ('hyalin_drop_diabetic_glomerulus', 3), ('immature_glomerulus', 40), ('ischemic_glomerular_collapse', 16), ('karyorrhexis_glomerulonephritis', 5), ('membranous_nephropathy_holes', 6), ('membranous_nephropathy_spikes', 16), ('mesangial_hypercellularity', 60), ('mesangial_matrix_expansion', 111), ('mesangiolysis', 26), ('nodular_sclerosis_glomerulus', 33), ('parietal_cell_glomerulus', 20), ('periglomerular_fibrosis', 15), ('podocyte', 6), ('podocyte_hyperplasia', 25), ('podocyte_hypertrophy', 16), ('podocyte_reabsorption_droplet', 2), ('pseudocrescent', 8), ('solidified_glomerular_sclerosis_global', 24), ('spikes_glomerular_amyoidosis', 5), ('visceral_epithelial_cell', 20), ('visceral_epithelial_cell_capping', 3), ('wire_loop_glomerulus', 11)])

In [11]:
for key, item in test_ordered_dict_0.items():
  print(item, end=' ')
print()
for key, item in test_ordered_dict_1.items():
  print(item, end=' ')
print()
for key, item in test_ordered_dict_2.items():
  print(item, end=' ')

34 8 26 36 11 6 53 4 27 76 23 15 9 38 5 77 32 17 12 10 3 40 16 5 6 16 60 111 26 33 20 15 6 25 16 2 8 24 5 20 3 11
34 8 26 36 11 6 53 4 27 76 23 15 9 38 5 77 32 17 12 10 3 40 16 5 6 16 60 111 26 33 20 15 6 24 16 2 8 25 5 20 3 11
34 8 26 36 11 6 53 4 27 76 23 15 9 38 5 77 32 17 12 10 3 40 16 5 6 16 60 111 26 33 20 15 6 24 16 2 8 25 5 20 3 11

In [12]:
recreated_labels_list_0 = []
recreated_labels_list_1 = []
recreated_labels_list_2 = []

for cls_idx, (key, item) in enumerate(test_ordered_dict_0.items()):
  recreated_labels_list_0.extend([cls_idx]*item)
for cls_idx, (key, item) in enumerate(test_ordered_dict_1.items()):
  recreated_labels_list_1.extend([cls_idx]*item)
for cls_idx, (key, item) in enumerate(test_ordered_dict_2.items()):
  recreated_labels_list_2.extend([cls_idx]*item)

print(recreated_labels_list_0)
print(len(recreated_labels_list_0))
print(recreated_labels_list_1)
print(len(recreated_labels_list_1))
print(recreated_labels_list_2)
print(len(recreated_labels_list_2))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41]
990
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41]
990
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41]
990

In [13]:
# === compute class weights ===
class_weights_0 = compute_class_weight(class_weight="balanced", classes=np.unique(recreated_labels_list_0), y=recreated_labels_list_0)
class_weights_1 = compute_class_weight(class_weight="balanced", classes=np.unique(recreated_labels_list_1), y=recreated_labels_list_1)
class_weights_2 = compute_class_weight(class_weight="balanced", classes=np.unique(recreated_labels_list_2), y=recreated_labels_list_2)

print(*class_weights_0, sep=", ")
# print(*class_weights_1, sep=", ")
# print(*class_weights_2, sep=", ")

0.6932773109243697, 2.9464285714285716, 0.9065934065934066, 0.6547619047619048, 2.142857142857143, 3.9285714285714284, 0.444743935309973, 5.892857142857143, 0.873015873015873, 0.3101503759398496, 1.0248447204968945, 1.5714285714285714, 2.619047619047619, 0.6203007518796992, 4.714285714285714, 0.30612244897959184, 0.7366071428571429, 1.3865546218487395, 1.9642857142857142, 2.357142857142857, 7.857142857142857, 0.5892857142857143, 1.4732142857142858, 4.714285714285714, 3.9285714285714284, 1.4732142857142858, 0.39285714285714285, 0.21235521235521235, 0.9065934065934066, 0.7142857142857143, 1.1785714285714286, 1.5714285714285714, 3.9285714285714284, 0.9428571428571428, 1.4732142857142858, 11.785714285714286, 2.9464285714285716, 0.9821428571428571, 4.714285714285714, 1.1785714285714286, 7.857142857142857, 2.142857142857143

In [ ]:
train_ordered_dict_0
val_ordered_dict_0
test_ordered_dict_0

train_ordered_dict_1
val_ordered_dict_1
test_ordered_dict_1

train_ordered_dict_2
val_ordered_dict_2
test_ordered_dict_2

In [8]:
groupname2clsname = {"Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells": ['glomerular basement membrane duplication splitting',
                                                                                                'glomerular basement membrane thickening',
                                                                                                'hyalin drop diabetic glomerulus',
                                                                                                'membranous nephropathy holes',
                                                                                                'membranous nephropathy spikes',
                                                                                                'podocyte hyperplasia',
                                                                                                'podocyte hypertrophy',
                                                                                                'podocyte reabsorption droplet',
                                                                                                'spikes glomerular amyoidosis',
                                                                                                'visceral epithelial cell capping', \
                                                                                                'wire loop glomerulus',],\
                     "Mesangial and Endocapillary Lesions": ['endocapillary hypercellularity',
                                                             'exudative glomerulus',
                                                             'glomerul lipoprotein thrombus',
                                                             'glomerular congestion',
                                                             'glomerular hyaline pseudothrombus',
                                                             'glomerular thrombus',
                                                             'glomerulonephritis hyaline thrombus',
                                                             'glomerulus endotheliosis',
                                                             'mesangial hypercellularity',
                                                             'mesangial matrix expansion',
                                                             'mesangiolysis'], \
                     "Miscellaneous Lesions and Key Normal Structures": ['glomerulomegaly',
                                                                         'immature glomerulus',
                                                                         'parietal cell glomerulus',
                                                                         'podocyte',
                                                                         'visceral epithelial cell'], \
                     "Necrotizing and Crescentic Lesions": ['fibrinoid necrosis glomerulus',
                                                            'fibrocellular crescent', # subgroup: crescents
                                                            'fibrous crescent', # subgroup: crescents
                                                            'karyorrhexis glomerulonephritis',
                                                            'pseudocrescent'], \
                     "Tuft Sclerosis and Collapse": ['glomerular adhesion',
                                                     'glomerular collapse', # subgroup: capillary collapse
                                                     'glomerular foam cell',
                                                     'glomerular hyalinosis',
                                                     'glomerular obsolesce',
                                                     'glomerular segmental sclerosis', # subgroup: segmental sclerosis
                                                     'ischemic glomerular collapse', # subgroup: capillary collapse
                                                     'nodular sclerosis glomerulus', # subgroup: sclerosis
                                                     'periglomerular fibrosis',
                                                     'solidified glomerular sclerosis global'] # subgroup: sclerosis
}

In [10]:
clsname2groupname = {}
for grp_name, cls_names in groupname2clsname.items():
    for cls_name in cls_names:
        clsname2groupname[cls_name] = grp_name

In [11]:
parent_count_dict = {"Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells": 0, \
                     "Mesangial and Endocapillary Lesions": 0, \
                     "Miscellaneous Lesions and Key Normal Structures": 0, \
                     "Necrotizing and Crescentic Lesions": 0, \
                     "Tuft Sclerosis and Collapse": 0}

for cls_idx, (key, item) in enumerate(test_ordered_dict_0.items()):
    clsname = key.replace('_', ' ')
    grpname = clsname2groupname[clsname]
    parent_count_dict[grpname] += item

test_ordered_dict_parent_0 = collections.OrderedDict(sorted(parent_count_dict.items()))

In [13]:
recreated_labels_list_parent_0 = []

for cls_idx, (key, item) in enumerate(test_ordered_dict_parent_0.items()):
  print(key, item)
  recreated_labels_list_parent_0.extend([cls_idx]*item)

print(recreated_labels_list_parent_0)
print(len(recreated_labels_list_parent_0))

Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells 118
Mesangial and Endocapillary Lesions 331
Miscellaneous Lesions and Key Normal Structures 103
Necrotizing and Crescentic Lesions 86
Tuft Sclerosis and Collapse 352
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
990

In [14]:
# === compute class weights ===
class_weights_parent_0 = compute_class_weight(class_weight="balanced", classes=np.unique(recreated_labels_list_parent_0), y=recreated_labels_list_parent_0)

print(*class_weights_parent_0, sep=", ")

1.6779661016949152, 0.5981873111782477, 1.9223300970873787, 2.302325581395349, 0.5625

In [16]:
split0_table = []
split0_table.append(train_ordered_dict_0)
split0_table.append(val_ordered_dict_0)
split0_table.append(test_ordered_dict_0)
pd.DataFrame(split0_table, columns=list_of_categories, index=['train', 'val', 'test'])

,endocapillary_hypercellularity,exudative_glomerulus,fibrinoid_necrosis_glomerulus,fibrocellular_crescent,fibrous_crescent,glomerul_lipoprotein_thrombus,glomerular_adhesion,glomerular_basement_membrane_duplication_splitting,glomerular_basement_membrane_thickening,glomerular_collapse,...,podocyte,podocyte_hyperplasia,podocyte_hypertrophy,podocyte_reabsorption_droplet,pseudocrescent,solidified_glomerular_sclerosis_global,spikes_glomerular_amyoidosis,visceral_epithelial_cell,visceral_epithelial_cell_capping,wire_loop_glomerulus
train,103,25,76,106,34,19,157,14,79,229,...,19,73,48,7,25,73,14,61,8,32
val,34,8,25,35,12,6,52,4,27,76,...,7,24,16,2,9,25,4,21,2,11
test,34,8,26,36,11,6,53,4,27,76,...,6,25,16,2,8,24,5,20,3,11

In [17]:
split1_table = []
split1_table.append(train_ordered_dict_0)
split1_table.append(val_ordered_dict_0)
split1_table.append(test_ordered_dict_0)
pd.DataFrame(split1_table, columns=list_of_categories)
pd.DataFrame(split0_table, columns=list_of_categories, index=['train', 'val', 'test'])

,endocapillary_hypercellularity,exudative_glomerulus,fibrinoid_necrosis_glomerulus,fibrocellular_crescent,fibrous_crescent,glomerul_lipoprotein_thrombus,glomerular_adhesion,glomerular_basement_membrane_duplication_splitting,glomerular_basement_membrane_thickening,glomerular_collapse,...,podocyte,podocyte_hyperplasia,podocyte_hypertrophy,podocyte_reabsorption_droplet,pseudocrescent,solidified_glomerular_sclerosis_global,spikes_glomerular_amyoidosis,visceral_epithelial_cell,visceral_epithelial_cell_capping,wire_loop_glomerulus
train,103,25,76,106,34,19,157,14,79,229,...,19,73,48,7,25,73,14,61,8,32
val,34,8,25,35,12,6,52,4,27,76,...,7,24,16,2,9,25,4,21,2,11
test,34,8,26,36,11,6,53,4,27,76,...,6,25,16,2,8,24,5,20,3,11

In [18]:
split2_table = []
split2_table.append(train_ordered_dict_0)
split2_table.append(val_ordered_dict_0)
split2_table.append(test_ordered_dict_0)
pd.DataFrame(split2_table, columns=list_of_categories)
pd.DataFrame(split0_table, columns=list_of_categories, index=['train', 'val', 'test'])

,endocapillary_hypercellularity,exudative_glomerulus,fibrinoid_necrosis_glomerulus,fibrocellular_crescent,fibrous_crescent,glomerul_lipoprotein_thrombus,glomerular_adhesion,glomerular_basement_membrane_duplication_splitting,glomerular_basement_membrane_thickening,glomerular_collapse,...,podocyte,podocyte_hyperplasia,podocyte_hypertrophy,podocyte_reabsorption_droplet,pseudocrescent,solidified_glomerular_sclerosis_global,spikes_glomerular_amyoidosis,visceral_epithelial_cell,visceral_epithelial_cell_capping,wire_loop_glomerulus
train,103,25,76,106,34,19,157,14,79,229,...,19,73,48,7,25,73,14,61,8,32
val,34,8,25,35,12,6,52,4,27,76,...,7,24,16,2,9,25,4,21,2,11
test,34,8,26,36,11,6,53,4,27,76,...,6,25,16,2,8,24,5,20,3,11

## From the KI paper
### Figures
- Figure 1 - Sclerosis and Collapse:
  - Capsular adhesion
  - Segmental sclerosis with visceral epithelial cell cappping
  - Segmental sclerosis with hyalinosis
  - Capillary collapse with visceral epithelial hyperplasia
  - Ischemic glomerular collapse
  - Segmental intracapillary foam cells with capping by visceral epithelial cells
- Figure 2 - Glomerular Basement Membrane (GBM) and Bowman's Capsule:
  - GBM duplication
  - GBM spikes
  - Glomerular amyloid spicules
  - Capillary microaneurysm
  - Wire loop lesions
  - Capsular hyaline drop
- Figure 3 - Mesangial and Endothelial Lesions:
  - Mesangial hypercellularity
  - Nodular glomerulosclerosis
  - Mesangiolysis
  - Membranoproliferative glomerulonephritis pattern
  - Exudative glomerulonephritis
  - Endotheliosis
- Figure 4 - Capillary and Extracapillary lesions
  - Fibrinoid necrosis
  - Cellular crescent with endocapillary hypercellularity
  - Fibrous crescent
  - Glomerular congestion and capillary thrombi
  - Pseudocrescent in collapsing glomerulopathy
  - Obsolescent glomerulus

### Table 1
- Tuft Sclerosis and Collapse
- Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells
- Mesangial and Endocapillary Lesions
- Necrotizing and Crescentic Lesions
- Miscellaneous Lesions and Key Normal Structures

In [ ]:
['endocapillary_hypercellularity - 0', # G3: Mesangial and Endocapillary Lesions
 'exudative_glomerulus - 1', # G3: Mesangial and Endocapillary Lesions
 'fibrinoid_necrosis_glomerulus - 2', # G4: Necrotizing and Crescentic Lesions
 'fibrocellular_crescent - 3', # G4: Necrotizing and Crescentic Lesions - crescent
 'fibrous_crescent - 4', # G4: Necrotizing and Crescentic Lesions - crescent
 'glomerul_lipoprotein_thrombus - 5', # G3: Mesangial and Endocapillary Lesions
 'glomerular_adhesion - 6', # G1: Tuft Sclerosis and Collapse
 'glomerular_basement_membrane_duplication_splitting - 7', # G2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells
 'glomerular_basement_membrane_thickening - 8', #
 'glomerular_collapse - 9', #
 'glomerular_congestion - 10', # G3: Mesangial and Endocapillary Lesions
 'glomerular_foam_cell - 11', # G1: Tuft Sclerosis and Collapse
 'glomerular_hyaline_pseudothrombus - 12', # G3: Mesangial and Endocapillary Lesions
 'glomerular_hyalinosis - 13', # G1: Tuft Sclerosis and Collapse
 'glomerular_obsolesce - 14', # G1: Tuft Sclerosis and Collapse
 'glomerular_segmental_sclerosis - 15', #  G1: Tuft Sclerosis and Collapse - sclerosis
 'glomerular_thrombus - 16', # G3: Mesangial and Endocapillary Lesions
 'glomerulomegaly - 17', # G5: Miscellaneous Lesions and Key Normal Structures
 'glomerulonephritis_hyaline_thrombus - 18', #
 'glomerulus_endotheliosis - 19', # G3: Mesangial and Endocapillary Lesions
 'hyalin_drop_diabetic_glomerulus - 20', # G2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells (check again)
 'immature_glomerulus - 21', # G5: Miscellaneous Lesions and Key Normal Structures
 'ischemic_glomerular_collapse - 22', # G1: Tuft Sclerosis and Collapse - capillary collapse
 'karyorrhexis_glomerulonephritis - 23', # G4: Necrotizing and Crescentic Lesions
 'membranous_nephropathy_holes - 24', #
 'membranous_nephropathy_spikes - 25', #
 'mesangial_hypercellularity - 26', # G3: Mesangial and Endocapillary Lesions
 'mesangial_matrix_expansion - 27', # G3: Mesangial and Endocapillary Lesions
 'mesangiolysis - 28', # G3: Mesangial and Endocapillary Lesions
 'nodular_sclerosis_glomerulus - 29', # G1: Tuft Sclerosis and Collapse - sclerosis
 'parietal_cell_glomerulus - 30', # G5: Miscellaneous Lesions and Key Normal Structures (check again)
 'periglomerular_fibrosis - 31', # G1: Tuft Sclerosis and Collapse
 'podocyte - 32', # G5: Miscellaneous Lesions and Key Normal Structures
 'podocyte_hyperplasia - 33', #
 'podocyte_hypertrophy - 34', #
 'podocyte_reabsorption_droplet - 35', # G2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells
 'pseudocrescent - 36', # G4: Necrotizing and Crescentic Lesions
 'solidified_glomerular_sclerosis_global - 37', # G1: Tuft Sclerosis and Collapse - sclerosis (or global sclerosis)
 'spikes_glomerular_amyoidosis - 38', #
 'visceral_epithelial_cell - 39', # G5: Miscellaneous Lesions and Key Normal Structures
 'visceral_epithelial_cell_capping - 40', # G2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells (check again)
 'wire_loop_glomerulus - 41'] # G2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells

In [1]:
# GROUP 1: Tuft Sclerosis and Collapse
G1 = ['glomerular_adhesion - (adhesion, isolated (synechia)) - 6',
      'glomerular_collapse - (capillary collapse) - 9', # subgroup: capillary collapse
      'glomerular_foam_cell - (foam cell) - 11',
      'glomerular_hyalinosis - (hyalinosis) - 13',
      'glomerular_obsolesce - (obsolescent glomerulus) - 14',
      'glomerular_segmental_sclerosis - (segmental sclerosis) - 15', # subgroup: segmental sclerosis
      'ischemic_glomerular_collapse - (ischemic-type glomerular collapse) - 22', # subgroup: capillary collapse
      'nodular_sclerosis_glomerulus - (nodular sclerosis) - 29', # subgroup: sclerosis
      'periglomerular_fibrosis - (periglomerular fibrosis) - 31',
      'solidified_glomerular_sclerosis_global - (global sclerosis (solidified glomerulus)) - 37'] # subgroup: sclerosis

# GROUP 2: Glomerular Basement Membrane (GBM), Bowman's Capsule, Epithelial Cells
G2 = ['glomerular_basement_membrane_duplication_splitting - (GBM duplication) - 7',
      'glomerular_basement_membrane_thickening - (thickened capillary wall) - 8',
      'hyalin_drop_diabetic_glomerulus - (capsular hyaline drop) - 20',
      'membranous_nephropathy_holes - (GBM luciencies (craters)) - 24',
      'membranous_nephropathy_spikes - (GBM spikes) - 25',
      'podocyte_hyperplasia - (visceral epithelial cell hyperplasia) - 33',
      'podocyte_hypertrophy - (visceral epithelial cell hypertropy) - 34',
      'podocyte_reabsorption_droplet - (visceral epithelial cell protein reabsorption droplets) - 35',
      'spikes_glomerular_amyoidosis - (GBM spicules) - 38',
      'visceral_epithelial_cell_capping - (visceral epithelial cell capping) - 40',
      'wire_loop_glomerulus - (wire loop) - 41']

# GROUP 3: Mesangial and Endocapillary Lesions
G3 = ['endocapillary_hypercellularity - (endocapillary hypercellularity) - 0',
      'exudative_glomerulus - (exudative) - 1',
      'glomerul_lipoprotein_thrombus - (lipoprotein thrombus) - 5',
      'glomerular_congestion - (glomerular congestion) - 10',
      'glomerular_hyaline_pseudothrombus - (hyaline pseudothrombus) - 12',
      'glomerular_thrombus - (thrombus) - 16',
      'glomerulonephritis_hyaline_thrombus - (intraglomerular leukocyte infiltration) - 18',
      'glomerulus_endotheliosis - (endotheliosis) - 19',
      'mesangial_hypercellularity - (mesangial hypercellularity) - 26',
      'mesangial_matrix_expansion - (mesangial matrix expansion) - 27',
      'mesangiolysis - (mesangiolysis) - 28']

# GROUP 4: Necrotizing and Crescentic Lesions
G4 = ['fibrinoid_necrosis_glomerulus - (fibrinoid necrosis) - 2',
      'fibrocellular_crescent - (fibrocellular crescent) - 3', # subgroup: crescents
      'fibrous_crescent - (fibrous crescent) - 4', # subgroup: crescents
      'karyorrhexis_glomerulonephritis - (karyorrhexis) - 23',
      'pseudocrescent - (pseudocrescent) - 36']

# GROUP 5: Miscellaneous Lesions and Key Normal Structures
G5 = ['glomerulomegaly - (glomerulomegaly) - 17',
      'immature_glomerulus - (immature glomerulus) - 21',
      'parietal_cell_glomerulus - (parietal epithelial cell) - 30',
      'podocyte - (podocyte) - 32',
      'visceral_epithelial_cell - (visceral epithelial cell) - 39']

In [2]:
len(G1) + len(G2) + len(G3) + len(G4) + len(G5)

42

In [4]:
concept_raw_list = np.load('../../datasets/GlomCrawl/concepts/concepts_raw.npy')
cls_name_list = np.load('../../datasets/GlomCrawl/concepts/cls_names.npy')
concept2cls = np.load('../../datasets/GlomCrawl/concepts/concept2cls.npy')

In [5]:
print(len(concept_raw_list))
print(len(cls_name_list))
print(len(concept2cls))

1557
42
1557

In [6]:
cls_name_list

array(['endocapillary hypercellularity', 'exudative glomerulus',
       'fibrinoid necrosis glomerulus', 'fibrocellular crescent',
       'fibrous crescent', 'glomerul lipoprotein thrombus',
       'glomerular adhesion',
       'glomerular basement membrane duplication splitting',
       'glomerular basement membrane thickening', 'glomerular collapse',
       'glomerular congestion', 'glomerular foam cell',
       'glomerular hyaline pseudothrombus', 'glomerular hyalinosis',
       'glomerular obsolesce', 'glomerular segmental sclerosis',
       'glomerular thrombus', 'glomerulomegaly',
       'glomerulonephritis hyaline thrombus', 'glomerulus endotheliosis',
       'hyalin drop diabetic glomerulus', 'immature glomerulus',
       'ischemic glomerular collapse', 'karyorrhexis glomerulonephritis',
       'membranous nephropathy holes', 'membranous nephropathy spikes',
       'mesangial hypercellularity', 'mesangial matrix expansion',
       'mesangiolysis', 'nodular sclerosis glomerulus',
       'parietal cell glomerulus', 'periglomerular fibrosis', 'podocyte',
       'podocyte hyperplasia', 'podocyte hypertrophy',
       'podocyte reabsorption droplet', 'pseudocrescent',
       'solidified glomerular sclerosis global',
       'spikes glomerular amyoidosis', 'visceral epithelial cell',
       'visceral epithelial cell capping', 'wire loop glomerulus'],
      dtype='<U50')

In [8]:
concept2cls[-1]

41.0